changed album list from table to collection
andresmurillas-experis/pruebaITunes pull request #15
Opened 2023-03-10 11:52 UTC by andresmurillas-experis

2023-03-10 12:13 UTC, jose-maria-jimenez requested changes

2023-03-10 12:13 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistDetail/ViewComponents/CollectionViewCell.swift
> +class CollectionViewCell: UICollectionViewCell {
final class

2023-03-10 12:13 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistDetail/ViewComponents/CollectionViewCell.swift
> +    @IBOutlet weak var albumName: UILabel!
private outlet

2023-03-10 12:13 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistDetail/ViewComponents/CollectionViewCell.swift
> +class CollectionViewCell: UICollectionViewCell {
mejora el naming

2023-03-10 12:41 UTC, andresmurillas-experis commented
aun no esta listo, quiero meter las imagenes de las url de album

2023-03-13 11:04 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistDetail/ViewComponents/AlbumViewCell.swift
> +    var image: UIImage! {
no ponemos variables con !

2023-03-13 11:41 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistDetail/ViewComponents/AlbumViewCell.swift
> +                self?.image = image ?? UIImage()
Todo lo que tienes ahora está ok y funciona, pero no hace falta tener una variable solo para en el didSet cambiar el albumCover.image. Puedes setearlo aquí directamente. self?.albumCover.image = image.

2023-03-13 11:47 UTC, jose-maria-jimenez requested changes

2023-03-13 11:47 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistDetail/ViewComponents/AlbumViewCell.swift
> +                self?.albumCover.image = image ?? UIImage()
UIImageView.image es opcional, así que no tienes que darle un ?? UIImage()

2023-03-13 11:53 UTC, jose-maria-jimenez approved these changes

2023-03-13 11:54 UTC, merged