created app dependencies resolver for download client
andresmurillas-experis/pruebaITunes pull request #20
Opened 2023-03-24 11:11 UTC by andresmurillas-experis

2023-03-29 09:36 UTC, jose-maria-jimenez requested changes

2023-03-29 09:36 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistDetail/Presenter/ArtistDetailPresenter.swift
> -    let downloadClient = DownloadClient()
no te cargues el client, y resuélvelo en el init

2023-03-29 09:36 UTC, jose-maria-jimenez commented on PruebaItunes/ITunes/AppDependencies.swift
> +    }
Si no lo haces opcional, tampoco te hace falta el setNavigationController, porque se lo pasas por constructor al crear el AppDependencies

2023-03-29 09:36 UTC, jose-maria-jimenez commented on PruebaItunes/ITunes/AppDependencies.swift
> +    }
el coordinator no tiene que devolver dependencias resolver.

2023-03-29 09:36 UTC, jose-maria-jimenez commented on PruebaItunes/ITunes/AppDependencies.swift
> +    func goTo(_ artistDetailView: ArtistDetailViewController) {
no tiene que recibir la vista a la que va, si no que tiene que ser goToDetailView(), y en la implementación utilizas el resolver para obtener viewcontroller, presenter y hacer el push de la vista bien configurada

2023-03-29 09:56 UTC, andresmurillas-experis commented on PruebaItunes/ITunes/AppDependencies.swift
> +    }
Pero en SceneDelegate necesito appDependancies antes de poder crear el navigator
```swift
let appDependencies = AppDependencies()
let initialView: ArtistListViewController = appDependencies.resolve()
let nav = UINavigationController(rootViewController: initialView)
```

2023-03-29 09:59 UTC, andresmurillas-experis commented on PruebaItunes/ITunes/AppDependencies.swift
> +    func goTo(_ artistDetailView: ArtistDetailViewController) {
hm vale, yo pensaba que luego podría usar polimorfismo para tener un método goTo() que me llevase a cualquier vista

2023-03-29 10:00 UTC, jose-maria-jimenez commented on PruebaItunes/ITunes/AppDependencies.swift
> +    }
estás pasándole un rootViewController en el init del NavigationController, investiga otras maneras

2023-03-29 10:01 UTC, jose-maria-jimenez commented on PruebaItunes/ITunes/AppDependencies.swift
> +    func goTo(_ artistDetailView: ArtistDetailViewController) {
no, justo el coordinator tiene que saber llegar a todas las vistas.

2023-03-29 10:14 UTC, jose-maria-jimenez requested changes

2023-03-29 10:14 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistDetail/Presenter/ArtistDetailPresenter.swift
> +    let downloadClient: DownloadClient
private

2023-03-29 10:14 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistDetail/Presenter/ArtistDetailPresenter.swift
> +    init(artistDetailView: ArtistDetailViewController? = nil, dataTask: URLSessionDataTask? = nil, artist: ArtistViewModel? = nil, downloadClient: DownloadClient, appDependencies: AppDependenciesReso
no tienes que recibir el downloadclient por parámetro, para eso tenemos el resolver...

2023-03-30 08:19 UTC, jose-maria-jimenez requested changes

2023-03-30 08:19 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistDetail/Presenter/ArtistDetailPresenter.swift
> +        let client: DownloadClient = appDependencies.resolve()
no instancies aquí un nievo client cuando lo tienes en la variable de clase....

2023-03-30 08:19 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistDetail/Presenter/ArtistDetailPresenter.swift
> +    init(artistDetailView: ArtistDetailViewController? = nil, dataTask: URLSessionDataTask? = nil, artist: ArtistViewModel? = nil, appDependencies: AppDependenciesResolver) {
el presenter solo necesita el appDependencies. Los demás parámetros no hacen falta. El view lo tendrá que setear el coordinator antes de devolver la vista. El datatask ya es cosa de la librería de red. El viewModel se seseará con el setArtis

2023-03-30 08:19 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistDetail/View/ArtistDetailViewController.swift
> +    func setPresenter(_ presenter: ArtistDetailPresenter)
mejor quitar el setPresenter y quitar que sea opcional. Pasar el presenter por init. Eso te impedirá proporcionar el ViewController desde el AppDependencies. Pero da igual, lo proporcionas desde el coordinator, ahí sí podrás.

2023-03-30 08:19 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistList/Presenter/ArtistListPresenter.swift
> +    init(dataTask: URLSessionDataTask? = nil, artistListView: ArtistListViewController? = nil, appDependencies: AppDependenciesResolver) {
mismos comentarios, solo hace falta el appdependencies. La vista la configuras en el coordinator al generar la vista.

2023-03-30 08:19 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistList/Presenter/ArtistListPresenter.swift
> +        coordinator.goToDetailViewWithPresenter(presenter)
el coordinator no tiene que recibir el presenter de destino. El coordinator tiene que encargarse de la navegación. Lo que le tienes que pasar al coordinator es el artist, para cuando crees el presenter en el coordinator, poder hacer presenter.setArtist

2023-03-30 08:19 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistList/Presenter/ArtistListPresenter.swift
> +        let client: DownloadClient = appDependencies.resolve()
client variable de clase

2023-03-30 08:19 UTC, jose-maria-jimenez commented on PruebaItunes/ITunes/AppDependencies.swift
> +    weak var appDependencies: AppDependencies?
siguen siendo opcionales cuando por constructor se las pasas no opcionales

2023-03-30 08:19 UTC, jose-maria-jimenez commented on PruebaItunes/ITunes/AppDependencies.swift
> +}
varios de estos métodos se pueden poner en la extensión que te comenté al principio y así no tendría que darle implementación AppDependencies

2023-03-30 08:19 UTC, jose-maria-jimenez commented on PruebaItunes/SceneDelegate.swift
> +        let initialView: ArtistListViewController = appDependencies.resolve()
mejor que forzar aquí el tipo a ArtistListViewController, mejor que el appdepencies tenga un método func getInitialViewController() -> UIViewController, y ahí devuelves el ArtistListViewController. De hecho, mejor que ese método esté en el coordinator.

2023-03-30 08:19 UTC, jose-maria-jimenez commented on PruebaItunes/SceneDelegate.swift
> +        initialView.setPresenter(appDependencies.resolve())
las vistas que devuelva el coordinator ya tiene que tener el presenter seteado, con todos los cambios mencionados esto debería quitarse.

2023-03-31 08:52 UTC, jose-maria-jimenez requested changes

2023-03-31 08:52 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistDetail/View/ArtistDetailViewController.swift
> +    private var presenter: ArtistDetailPresenter
por qué has cambiado el tipo?

2023-03-31 08:52 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistList/Presenter/ArtistListPresenter.swift
> +    }
este es un método del presenter protocol, debería ir en su correspondiente extensión...

2023-03-31 08:52 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistList/View/ArtistListViewController.swift
> +    private var presenter: ArtistListPresenterProtocol?
por qué opcional si lo recibe por constructor no opcional

2023-03-31 08:52 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistList/View/ArtistListViewController.swift
> +    init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?, presenter: ArtistListPresenter) {
tipo presenter en vez de presenter protocol

2023-03-31 08:52 UTC, jose-maria-jimenez commented on PruebaItunes/ITunes/AppDependencies.swift
> +}
hay métodos que puedes extender en una extension AppDependenciesResolver { }, para así no tener que dar implementación en AppDepedencies. Investiga cuales.

Además, deberías devolver para todos los tipos los protocolos. ArtisListViewListViewProtocol, ArtistListPresenterProtocol....

2023-03-31 08:52 UTC, jose-maria-jimenez commented on PruebaItunes/ITunes/AppDependencies.swift
> +        return artistListPresenter
esto se puede simplificar a return ArtlistListPresenter(appDependencies: self), y como solo es una línea se puede omitir el return

2023-03-31 08:52 UTC, jose-maria-jimenez commented on PruebaItunes/SceneDelegate.swift
> +        nav.pushViewController(initialView, animated: false)
aquí ya vimos el otro método para setear los viewcontrollers iniciales sin tener que hacer push. De hecho, mira cómo setearlos sin tener que llamar al setViewControllers

2023-03-31 11:09 UTC, jose-maria-jimenez requested changes

2023-03-31 11:09 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistList/Presenter/ArtistListPresenter.swift
> +        let coordinator: Coordinator = appDependencies.resolve()
coordinator puedes sacarlo a una variable computada dentro de private extension

2023-03-31 11:09 UTC, jose-maria-jimenez commented on PruebaItunes/ITunes/AppDependencies.swift
> +    func getNavigator() -> UINavigationController
entiendo que has puesto este método porque no tenías acceso al navigation controller. No hace falta, en la extensión solo tienen que ir los métodos que puedas proporcionar por defecto. Si necesitas un navigation controller para pasárselo al Coordinator, el resolve() -> Coordinator, no se implementa en la extensión. Se implementa cuando AppDependencies implemente AppDependencies resolver, te dirá que te falta un método puesto que no está en la extensión del protocolo.

Como AppDependencies sí tiene navigationController, ya puedes implementar el resolve que falta

2023-03-31 11:46 UTC, jose-maria-jimenez requested changes

2023-03-31 11:46 UTC, jose-maria-jimenez commented on PruebaItunes/ITunes/AppDependencies.swift
> +    }
Este comentario no se me guardó. Todos los métodos que estén extendidos por defectos en una extensión de protocolo, tienen que estar declarados en el protocolo mismo. En la extensión se les da implementación por defecto, esta parte la tienes bien, pero tienen que aparecer también su declaración en el protocolo.

2023-04-03 08:55 UTC, jose-maria-jimenez approved these changes

2023-04-03 08:55 UTC, merged