split download code
andresmurillas-experis/pruebaITunes pull request #7
Opened 2023-03-01 12:34 UTC by andresmurillas-experis

2023-03-01 12:55 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistListViewController.swift
> +    func download(from url: String, handler: @escaping (Data) -> Data) {
no entiendo por qué (Data) -> Data. Es más cómodo que devuelvas los objetos parseados del servicio. Y no hace falta que devuelvas data, la cosa de la closure es que la va a recibir por parámetro desde donde la llames.

osea
([ArtistViewModel]) -> Void

2023-03-01 12:55 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistListViewController.swift
>                  print("Error unwrapping data constant")
en base al anterior comentario aquí puedes llamar a tu func decodeJSON y pasarle el array a la closure.

2023-03-01 12:55 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistListViewController.swift
> +    var data = Data()
no necesitas el data aquí fuera.

2023-03-01 12:55 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistListViewController.swift
> +            return data
no tiene sentido que aquí devuelvas el mismo data que te viene por parámetro de entrada. De hecho, revisa los warnings. En la línea 81 te está avisando de que el resultado de handler(data) no se está usando. Eso es porque como has declarado la closure (Data) -> Data, en la línea 81 tienes un data como resultado.

Más abajo hay más comentarios respecto a la clousure.

2023-03-01 12:55 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistListViewController.swift
> +        artistList = decodeJSONFromData(data: data)
si seteas artistList fuera de la closure, lo estás haciendo antes de que se llame al servicio. Lo correcto de esta línea sería DENTRO de la closure. Una vez tengas todos los cambios de más abajo, tu closure debería recibir un array de viewModels

2023-03-01 13:09 UTC, andresmurillas-experis commented on PruebaItunes/ArtistListViewController.swift
> +    func download(from url: String, handler: @escaping (Data) -> Data) {
que tomaría por parametro de entrada?

2023-03-01 13:27 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistListViewController.swift
> +    func download(from url: String, handler: @escaping (Data) -> Data) {
está puesto en el comment. Sería:
handler: @escaping ([ArtistViewModel]) -> Void

2023-03-02 10:01 UTC, jose-maria-jimenez requested changes

2023-03-02 10:01 UTC, jose-maria-jimenez commented on PruebaItunes/ArtistListViewController.swift
> +    func download(from url: String, handler: @escaping (ArtistListViewController, [ArtistViewModel]) -> Void = { (ArtistListViewController, artistList) in
la closure sigue estando mal, la closure tiene que ser como en los otros comentarios se ha dicho ([ArtistViewModel]) -> Void, no (ArtistListViewController, [ArtistiViewModel]) -> Void. Además le estás dando un valor por defecto, por eso donde la usas en la línea 24, te deja llamar a la función solo con la URL.

Eso está mal, no le des valor por defecto e implementa la closure cuando llames en la línea 24 a download.

2023-03-02 11:09 UTC, merged